//BIBLIOTECA QUE USAMOS PARA FUNCIONES DE ENTRADA Y SALIDA
#include<stdio.h>
//NOS PERMITE DAR UNA POCISION AL CURSOR PARA PODER MANDAR A IMPRIMIR LAS COORDENADAS
#include<windows.h>

int main(){
	
	//OBJETO QUE USAREMOS QUE SE MOVERA CON LAS COORDENADAS QUE USAREMOS
	printf("*");
	
	//ESTE SERA NUESTRO HANDEL O NUESTRO IDENTIFICADOR PARA NUESTRA CONSOLA
	//EL NOMBRE DE NUESTRO HANDLE PUEDE SER EL QUE SEA PERO EL QUE USAMOS EN ESTE CASO ES UNO DE LOS QUE USAMOS MAS COMUNMENTE
	HANDLE hCon;
	
	//CON ESTE GETSTDHANDLE SE RECUPERAEL IDENTIFICADOR DE LA CONSOLA EL CUAL TIENE UN ORDEN CON UN PARAMETRO COMO EL QUE ESTAMOS USANDO QUE SERIA EL STD_OUTPUT_HANDLE CON EL QUE LO QUE HACEMOS ES RECUPERAR EL CONTROL DE LA SALIDA DE LA CONSOLA 
	hCon = GetStdHandle(STD_OUTPUT_HANDLE);
	
	//COORDENADAS DE NUESTRA VENTANA O HANDLE PARA NUESTROS OBJETOS/OBSTACULOS
	//COORD EN NUESTRA ESTUCTURA Y DWPOS ES NUESTRO OBJETO
	COORD dwPos;
	dwPos.X = 4;
	dwPos.Y = 5;
	
	//CON ESTA FUNCION DAMOS POSICION AL CURSOR CONTIENE 2 PARAMETROS EL PRIMERO ES EL HANDEL Y UNA ESTRUCTURA DE DATOS
	//EL HANDEL ES EL NOMBRE PARA EL SISTEMA PARA LA VENTANA QUE ES UNA NUESTRA CONSOLA DE EJECUCION PARA ESTE CASO
	SetConsoleCursorPosition(hCon, dwPos);
	printf("*");
	
	return 0;
	
}